import { Link } from 'react-router-dom';
import { Page } from '../components/Layout';

export function Certification() { return <Page title="Certificación de especialistas"><p>El Consejo convoca a médicos especialistas con formación profesional en Cardiología Clínica, Cardiología Pediátrica y subespecialidades cardiológicas para participar en el proceso de certificación.</p><h2>Especialidades</h2><ul><li>Cardiología Clínica</li><li>Cardiología Pediátrica</li><li>Cardiología Intervencionista</li><li>Electrofisiología Cardiaca</li><li>Cardiología Intervencionista en Cardiopatías Congénitas</li><li>Ecocardiografía Adultos</li><li>Ecocardiografía Pediátrica</li><li>Rehabilitación Cardiaca</li></ul><div className="callout"><b>Examen teórico 2026:</b> sábado 24 de octubre de 2026.<br /><b>Sede:</b> Ciudad de México.</div></Page>; }
export function Recertification() { return <Page title="Vigencia o recertificación"><p>La vigencia de la certificación puede obtenerse por currículo o mediante examen teórico-práctico, de acuerdo con los requisitos establecidos por el Consejo.</p><h2>Vigencia por currículum</h2><p>El proceso considera actividades curriculares y documentación académica conforme a la guía de criterios de evaluación.</p><h2>Vigencia por examen</h2><p>La acreditación se realiza mediante examen teórico y práctico, previa integración del expediente requerido.</p></Page>; }
export function Courses() { return <Page title="Cursos avalados"><p>Eventos de Educación Médica Continua dirigidos a especialistas en Cardiología con aval del Consejo. Los eventos pueden otorgar puntos curriculares válidos para el proceso de vigencia.</p><div className="course"><b>Cursos 2026</b><p>Consulta los eventos publicados y su información correspondiente.</p></div></Page>; }
export function Patient() { return <Page title="Guía del paciente"><h2>¿Qué es la vigencia de la certificación?</h2><p>Un especialista certificado debe actualizar sus conocimientos y mantener vigente su certificación. El directorio permite verificar la vigencia registrada.</p><h2>¿Cómo saber si mi médico está certificado?</h2><p>Consulta el directorio del Consejo para verificar el estatus de tu especialista.</p><Link className="btn" to="/directorio">Consultar directorio</Link></Page>; }
export function Directory() { return <Page title="Directorio"><p>Centros formadores y establecimientos con reconocimiento del Consejo. Esta réplica contiene una muestra de la estructura; los datos completos pueden conectarse posteriormente a una API o base de datos.</p><div className="directory"><b>Ciudad de México</b><p>Instituto Nacional de Cardiología — Cardiología Clínica, Cardiología Pediátrica y subespecialidades.</p><p>Centro Médico Nacional 20 de Noviembre — diversas especialidades cardiológicas.</p><p>Hospital Español de México — Cardiología Clínica, Intervencionista y Ecocardiografía.</p></div></Page>; }
export function Regulation() { return <Page title="Regulación"><p>Sección preparada para integrar estatutos, reglamentos, manuales y código de ética.</p></Page>; }
