import React from 'react'; import {Routes,Route,Link} from 'react-router-dom';
const services=[['Certificación de especialistas','Requisitos para inscripción a examen teórico-práctico.','/certificacion'],['Vigencia o recertificación','Requisitos para solicitud por currículo o por examen.','/recertificacion'],['Aval de eventos de Educación Médica Continua','Cursos avalados, próximos eventos y requisitos.','/cursos'],['Paciente','Verifique que su médico tratante tiene certificación.','/paciente']];
function Header(){return <><div className="top"><div>Consejo Mexicano de Cardiología</div><div>55 5485 1405 · 9:00 a 16:00 hrs</div></div><header><Link to="/" className="brand"><span className="heart">♥</span><span>CONSEJO MEXICANO<br/><b>DE CARDIOLOGÍA</b></span></Link><nav><Link to="/">Inicio</Link><Link to="/certificacion">Certificación</Link><Link to="/recertificacion">Recertificación</Link><Link to="/cursos">Cursos</Link><Link to="/directorio">Directorio</Link><Link to="/paciente">Paciente</Link></nav></header></>}
function Footer(){return <footer><div><b>CONSEJO MEXICANO DE CARDIOLOGÍA</b><p>Calle Juan Badiano No. 1, Edif. Santiago Galas 1er piso, Col. Belisario Domínguez Sección XVI, Tlalpan, CDMX.</p></div><div><b>Contacto</b><p>55 5485 1405<br/>Horario: 9:00 a 16:00 hrs</p></div></footer>}
function Layout({children}){return <><Header/>{children}<Footer/></>}
function Home(){return <Layout><section className="hero"><div><span className="eyebrow">CERTIFICACIÓN · VIGENCIA · EDUCACIÓN</span><h1>Consejo Mexicano<br/><strong>de Cardiología</strong></h1><p>Reconocimiento y certificación de especialistas en cardiología, con información para médicos y pacientes.</p><div><Link className="btn" to="/certificacion">Conoce los procesos</Link><Link className="btn outline" to="/paciente">Guía del paciente</Link></div></div><div className="hero-art"><div className="circle">♡</div></div></section><section className="section"><div className="section-head"><span>Servicios</span><h2>Información para cada necesidad</h2></div><div className="cards">{services.map(([t,d,u],i)=><Link className="card" to={u} key={t}><span className="num">0{i+1}</span><h3>{t}</h3><p>{d}</p><span className="more">Ver más →</span></Link>)}</div></section><section className="notice"><div><span className="eyebrow">EXAMEN NACIONAL DE CERTIFICACIÓN 2026</span><h2>Tercera convocatoria</h2><p>Examen teórico: sábado 24 de octubre de 2026. Examen práctico: fecha asignada por el Consejo entre el 22 y 30 de octubre, en Ciudad de México.</p></div><Link className="btn" to="/certificacion">Consultar convocatoria</Link></section><section className="section light"><div className="columns"><div><span className="eyebrow">CURSOS AVALADOS</span><h2>Educación Médica Continua</h2><p>Consulta actividades académicas y eventos que cuentan con aval del Consejo y puntos curriculares válidos para el proceso de vigencia.</p><Link className="textlink" to="/cursos">Ver cursos →</Link></div><div><span className="eyebrow">CONACEM</span><h2>Idoneidad 2023–2028</h2><p>Información institucional y documentos regulatorios del Consejo Mexicano de Cardiología.</p><Link className="textlink" to="/regulacion">Ver regulación →</Link></div></div></section></Layout>}
function Page({title,children}){return <Layout><main className="page"><span className="eyebrow">CONSEJO MEXICANO DE CARDIOLOGÍA</span><h1>{title}</h1>{children}</main></Layout>}
function Certification(){return <Page title="Certificación de especialistas"><p>El Consejo convoca a médicos especialistas con formación profesional en Cardiología Clínica, Cardiología Pediátrica y subespecialidades cardiológicas para participar en el proceso de certificación.</p><h2>Especialidades</h2><ul><li>Cardiología Clínica</li><li>Cardiología Pediátrica</li><li>Cardiología Intervencionista</li><li>Electrofisiología Cardiaca</li><li>Cardiología Intervencionista en Cardiopatías Congénitas</li><li>Ecocardiografía Adultos</li><li>Ecocardiografía Pediátrica</li><li>Rehabilitación Cardiaca</li></ul><div className="callout"><b>Examen teórico 2026:</b> sábado 24 de octubre de 2026.<br/><b>Sede:</b> Ciudad de México.</div></Page>}
function Recert(){return <Page title="Vigencia o recertificación"><p>La vigencia de la certificación puede obtenerse por currículo o mediante examen teórico-práctico, de acuerdo con los requisitos establecidos por el Consejo.</p><h2>Vigencia por currículum</h2><p>El proceso considera actividades curriculares y documentación académica conforme a la guía de criterios de evaluación.</p><h2>Vigencia por examen</h2><p>La acreditación se realiza mediante examen teórico y práctico, previa integración del expediente requerido.</p></Page>}
function Courses(){return <Page title="Cursos avalados"><p>Eventos de Educación Médica Continua dirigidos a especialistas en Cardiología con aval del Consejo. Los eventos pueden otorgar puntos curriculares válidos para el proceso de vigencia.</p><div className="course"><b>Cursos 2026</b><p>Consulta los eventos publicados y su información correspondiente.</p></div></Page>}
function Patient(){return <Page title="Guía del paciente"><h2>¿Qué es la vigencia de la certificación?</h2><p>Un especialista certificado debe actualizar sus conocimientos y mantener vigente su certificación. El directorio permite verificar la vigencia registrada.</p><h2>¿Cómo saber si mi médico está certificado?</h2><p>Consulta el directorio del Consejo para verificar el estatus de tu especialista.</p><Link className="btn" to="/directorio">Consultar directorio</Link></Page>}
function Directory(){return <Page title="Directorio"><p>Centros formadores y establecimientos con reconocimiento del Consejo. Esta réplica contiene una muestra de la estructura; los datos completos pueden conectarse posteriormente a una API o base de datos.</p><div className="directory"><b>Ciudad de México</b><p>Instituto Nacional de Cardiología — Cardiología Clínica, Cardiología Pediátrica y subespecialidades.</p><p>Centro Médico Nacional 20 de Noviembre — diversas especialidades cardiológicas.</p><p>Hospital Español de México — Cardiología Clínica, Intervencionista y Ecocardiografía.</p></div></Page>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/certificacion" element={<Certification/>}/><Route path="/recertificacion" element={<Recert/>}/><Route path="/cursos" element={<Courses/>}/><Route path="/paciente" element={<Patient/>}/><Route path="/directorio" element={<Directory/>}/><Route path="/regulacion" element={<Page title="Regulación"><p>Sección preparada para integrar estatutos, reglamentos, manuales y código de ética.</p></Page>}/><Route path="*" element={<Home/>}/></Routes>}; export default App;
